; Item pool size constants for location-based randomization
; Use these constants to reference pool sizes

ROUTE29_POOL_SIZE EQU 3
ROUTE30_POOL_SIZE EQU 4
ROUTE31_POOL_SIZE EQU 4
ROUTE32_POOL_SIZE EQU 4
UNIONCAVE_POOL_SIZE EQU 5
SPROUTTOWER_POOL_SIZE EQU 4
ILEXFOREST_POOL_SIZE EQU 5
ROUTE36_POOL_SIZE EQU 5
ICEPATH_POOL_SIZE EQU 5
VICTORYROAD_POOL_SIZE EQU 6