; Trainer Variant System
; At battle start, randomly selects one of 3 possible teams (original + 2 variants)
; for eligible Johto trainers. Each entry in the table maps a (class, base_id) to
; two variant IDs. A random roll picks original (33%), variant1 (33%), or variant2 (33%).

CheckTrainerVariant::
	ld a, [wOtherTrainerClass]
	ld b, a
	ld a, [wOtherTrainerID]
	ld c, a
	ld hl, TrainerVariantTable
.loop:
	ld a, [hli]           ; class (or $FF terminator)
	cp $FF
	ret z                 ; no match, use original
	cp b
	jr nz, .skip3
	ld a, [hli]           ; base_id
	cp c
	jr nz, .skip2
	; Match found — hl points to variant1_id
	push hl
	ld a, 3
	call RandomRange      ; a = 0, 1, or 2
	pop hl
	or a
	ret z                 ; 0 = keep original
	dec a
	jr z, .use_var1
	; use variant 2
	inc hl
.use_var1:
	ld a, [hl]
	ld [wOtherTrainerID], a
	ret
.skip3:
	inc hl                ; skip base_id
.skip2:
	inc hl                ; skip variant1_id
	inc hl                ; skip variant2_id
	jr .loop

TrainerVariantTable:
; Format: db CLASS, BASE_ID, VARIANT1_ID, VARIANT2_ID
; Terminated by $FF

	db YOUNGSTER, JOEY1, JOEY1_V1, JOEY1_V2
	db YOUNGSTER, MIKEY, MIKEY_V1, MIKEY_V2
	db YOUNGSTER, ALBERT, ALBERT_V1, ALBERT_V2
	db YOUNGSTER, GORDON, GORDON_V1, GORDON_V2
	db YOUNGSTER, SAMUEL, SAMUEL_V1, SAMUEL_V2
	db YOUNGSTER, IAN, IAN_V1, IAN_V2
	db BUG_CATCHER, DON, DON_V1, DON_V2
	db BUG_CATCHER, WADE1, WADE1_V1, WADE1_V2
	db BUG_CATCHER, BUG_CATCHER_BENNY, BUG_CATCHER_BENNY_V1, BUG_CATCHER_BENNY_V2
	db BUG_CATCHER, AL, AL_V1, AL_V2
	db BUG_CATCHER, JOSH, JOSH_V1, JOSH_V2
	db BUG_CATCHER, ARNIE1, ARNIE1_V1, ARNIE1_V2
	db BUG_CATCHER, WAYNE, WAYNE_V1, WAYNE_V2
	db SAGE, CHOW, CHOW_V1, CHOW_V2
	db SAGE, NICO, NICO_V1, NICO_V2
	db SAGE, EDMOND, EDMOND_V1, EDMOND_V2
	db SAGE, JIN, JIN_V1, JIN_V2
	db SAGE, TROY, TROY_V1, TROY_V2
	db SAGE, NEAL, NEAL_V1, NEAL_V2
	db SAGE, LI, LI_V1, LI_V2
	db SAGE, JEFFREY, JEFFREY_V1, JEFFREY_V2
	db SAGE, PING, PING_V1, PING_V2
	db CAMPER, ROLAND, ROLAND_V1, ROLAND_V2
	db CAMPER, TODD1, TODD1_V1, TODD1_V2
	db CAMPER, IVAN, IVAN_V1, IVAN_V2
	db CAMPER, ELLIOT, ELLIOT_V1, ELLIOT_V2
	db CAMPER, SPENCER, SPENCER_V1, SPENCER_V2
	db CAMPER, TED, TED_V1, TED_V2
	db CAMPER, QUENTIN, QUENTIN_V1, QUENTIN_V2
	db PICNICKER, LIZ1, LIZ1_V1, LIZ1_V2
	db PICNICKER, GINA1, GINA1_V1, GINA1_V2
	db PICNICKER, BROOKE, BROOKE_V1, BROOKE_V2
	db PICNICKER, KIM, KIM_V1, KIM_V2
	db PICNICKER, TIFFANY1, TIFFANY1_V1, TIFFANY1_V2
	db PICNICKER, ERIN1, ERIN1_V1, ERIN1_V2
	db FISHER, JUSTIN, JUSTIN_V1, JUSTIN_V2
	db FISHER, RALPH1, RALPH1_V1, RALPH1_V2
	db FISHER, HENRY, HENRY_V1, HENRY_V2
	db FISHER, TULLY1, TULLY1_V1, TULLY1_V2
	db FISHER, MARVIN, MARVIN_V1, MARVIN_V2
	db FISHER, ANDRE, ANDRE_V1, ANDRE_V2
	db FISHER, RAYMOND, RAYMOND_V1, RAYMOND_V2
	db FISHER, WILTON1, WILTON1_V1, WILTON1_V2
	db FISHER, EDGAR, EDGAR_V1, EDGAR_V2
	db HIKER, RUSSELL, RUSSELL_V1, RUSSELL_V2
	db HIKER, DANIEL, DANIEL_V1, DANIEL_V2
	db HIKER, ANTHONY1, ANTHONY1_V1, ANTHONY1_V2
	db HIKER, PHILLIP, PHILLIP_V1, PHILLIP_V2
	db HIKER, LEONARD, LEONARD_V1, LEONARD_V2
	db HIKER, BENJAMIN, BENJAMIN_V1, BENJAMIN_V2
	db HIKER, ERIK, ERIK_V1, ERIK_V2
	db HIKER, MICHAEL, MICHAEL_V1, MICHAEL_V2
	db HIKER, TIMOTHY, TIMOTHY_V1, TIMOTHY_V2
	db BIRD_KEEPER, PETER, PETER_V1, PETER_V2
	db BIRD_KEEPER, BRYAN, BRYAN_V1, BRYAN_V2
	db BIRD_KEEPER, THEO, THEO_V1, THEO_V2
	db BIRD_KEEPER, TOBY, TOBY_V1, TOBY_V2
	db BIRD_KEEPER, DENIS, DENIS_V1, DENIS_V2
	db BIRD_KEEPER, VANCE1, VANCE1_V1, VANCE1_V2
	db LASS, CARRIE, CARRIE_V1, CARRIE_V2
	db LASS, BRIDGET, BRIDGET_V1, BRIDGET_V2
	db LASS, KRISE, KRISE_V1, KRISE_V2
	db LASS, DANA1, DANA1_V1, DANA1_V2
	db LASS, CONNIE1, CONNIE1_V1, CONNIE1_V2
	db SAILOR, EUGENE, EUGENE_V1, EUGENE_V2
	db SAILOR, HUEY1, HUEY1_V1, HUEY1_V2
	db SAILOR, TERRELL, TERRELL_V1, TERRELL_V2
	db SAILOR, KENT, KENT_V1, KENT_V2
	db SAILOR, ERNEST, ERNEST_V1, ERNEST_V2
	db SAILOR, HARRY, HARRY_V1, HARRY_V2
	db MEDIUM, MARTHA, MARTHA_V1, MARTHA_V2
	db MEDIUM, GRACE, GRACE_V1, GRACE_V2
	db BOARDER, RONALD, RONALD_V1, RONALD_V2
	db BOARDER, BRAD, BRAD_V1, BRAD_V2
	db BOARDER, DOUGLAS, DOUGLAS_V1, DOUGLAS_V2
	db SKIER, ROXANNE, ROXANNE_V1, ROXANNE_V2
	db SKIER, CLARISSA, CLARISSA_V1, CLARISSA_V2
	db BLACKBELT_T, YOSHI, YOSHI_V1, YOSHI_V2
	db BLACKBELT_T, LAO, LAO_V1, LAO_V2
	db BLACKBELT_T, NOB, NOB_V1, NOB_V2
	db BLACKBELT_T, LUNG, LUNG_V1, LUNG_V2
	db BLACKBELT_T, KENJI3, KENJI3_V1, KENJI3_V2
	db SCHOOLBOY, JACK1, JACK1_V1, JACK1_V2
	db SCHOOLBOY, ALAN1, ALAN1_V1, ALAN1_V2
	db SCHOOLBOY, CHAD1, CHAD1_V1, CHAD1_V2
	db SUPER_NERD, ERIC, ERIC_V1, ERIC_V2
	db SUPER_NERD, TERU, TERU_V1, TERU_V2
	db SUPER_NERD, MARKUS, MARKUS_V1, MARKUS_V2
	db SUPER_NERD, HUGH, HUGH_V1, HUGH_V2
	db PSYCHIC_T, GREG, GREG_V1, GREG_V2
	db PSYCHIC_T, NORMAN, NORMAN_V1, NORMAN_V2
	db PSYCHIC_T, MARK, MARK_V1, MARK_V2
	db PSYCHIC_T, PHIL, PHIL_V1, PHIL_V2
	db BEAUTY, VICTORIA, VICTORIA_V1, VICTORIA_V2
	db BEAUTY, SAMANTHA, SAMANTHA_V1, SAMANTHA_V2
	db BEAUTY, VALERIE, VALERIE_V1, VALERIE_V2
	db BEAUTY, OLIVIA, OLIVIA_V1, OLIVIA_V2
	db GENTLEMAN, PRESTON, PRESTON_V1, PRESTON_V2
	db GENTLEMAN, ALFRED, ALFRED_V1, ALFRED_V2
	db POKEMANIAC, LARRY, LARRY_V1, LARRY_V2
	db POKEMANIAC, ANDREW, ANDREW_V1, ANDREW_V2
	db POKEMANIAC, CALVIN, CALVIN_V1, CALVIN_V2
	db POKEMANIAC, SHANE, SHANE_V1, SHANE_V2
	db POKEMANIAC, BEN, BEN_V1, BEN_V2
	db POKEMANIAC, BRENT1, BRENT1_V1, BRENT1_V2
	db POKEMANIAC, RON, RON_V1, RON_V2
	db POKEMANIAC, ISSAC, ISSAC_V1, ISSAC_V2
	db POKEMANIAC, DONALD, DONALD_V1, DONALD_V2
	db POKEMANIAC, MILLER, MILLER_V1, MILLER_V2
	db POKEMANIAC, ZACH, ZACH_V1, ZACH_V2
	db POKEFANM, WILLIAM, WILLIAM_V1, WILLIAM_V2
	db POKEFANM, DEREK1, DEREK1_V1, DEREK1_V2
	db POKEFANM, BRANDON, BRANDON_V1, BRANDON_V2
	db POKEFANF, BEVERLY1, BEVERLY1_V1, BEVERLY1_V2
	db POKEFANF, RUTH, RUTH_V1, RUTH_V2
	db FIREBREATHER, BILL, BILL_V1, BILL_V2
	db FIREBREATHER, WALT, WALT_V1, WALT_V2
	db FIREBREATHER, RAY, RAY_V1, RAY_V2
	db SWIMMERM, SIMON, SIMON_V1, SIMON_V2
	db SWIMMERM, RANDALL, RANDALL_V1, RANDALL_V2
	db SWIMMERM, CHARLIE, CHARLIE_V1, CHARLIE_V2
	db SWIMMERM, GEORGE, GEORGE_V1, GEORGE_V2
	db SWIMMERM, BERKE, BERKE_V1, BERKE_V2
	db SWIMMERM, KIRK, KIRK_V1, KIRK_V2
	db SWIMMERM, MATHEW, MATHEW_V1, MATHEW_V2
	db SWIMMERF, ELAINE, ELAINE_V1, ELAINE_V2
	db SWIMMERF, PAULA, PAULA_V1, PAULA_V2
	db SWIMMERF, KAYLEE, KAYLEE_V1, KAYLEE_V2
	db SWIMMERF, SUSIE, SUSIE_V1, SUSIE_V2
	db SWIMMERF, DENISE, DENISE_V1, DENISE_V2
	db SWIMMERF, KARA, KARA_V1, KARA_V2
	db SWIMMERF, WENDY, WENDY_V1, WENDY_V2
	db JUGGLER, IRWIN1, IRWIN1_V1, IRWIN1_V2
	db TWINS, AMYANDMAY1, AMYANDMAY1_V1, AMYANDMAY1_V2
	db TWINS, ANNANDANNE1, ANNANDANNE1_V1, ANNANDANNE1_V2
	db COOLTRAINERM, NICK, NICK_V1, NICK_V2
	db COOLTRAINERM, AARON, AARON_V1, AARON_V2
	db COOLTRAINERM, ALLEN, ALLEN_V1, ALLEN_V2
	db COOLTRAINERM, RYAN, RYAN_V1, RYAN_V2
	db COOLTRAINERF, IRENE, IRENE_V1, IRENE_V2
	db COOLTRAINERF, JENN, JENN_V1, JENN_V2
	db COOLTRAINERF, KATE, KATE_V1, KATE_V2
	db COOLTRAINERF, GWEN, GWEN_V1, GWEN_V2
	db COOLTRAINERF, EMMA, EMMA_V1, EMMA_V2
	db COOLTRAINERF, LOIS, LOIS_V1, LOIS_V2
	db BURGLAR, DUNCAN, DUNCAN_V1, DUNCAN_V2
	db BURGLAR, EDDIE, EDDIE_V1, EDDIE_V2

	db $FF ; end of table
